# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For ore information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Cucumber Reports
      uses: deblockt/cucumber-report-annotations-action@v1.7
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}
        path: "./target/surefire-reports/src.test.resources.Testcases.json"     
      

    # Upload artifacts for code covergae result
    - name: Upload artifact for coverage result
      uses: actions/upload-artifact@v2
      with:
        name: results
        path: ./target/surefire-reports/src.test.resources.Testcases.json  
            # Upload artifacts for code covergae result
            
    - name: Upload artifact for html cucumber reports
      uses: actions/upload-artifact@v2
      with:
        name: results
        path: ./target/cucumber-html-reports  
        
